package model;
// Generated 15.12.2011 17:22:14 by Hibernate Tools 3.2.1.GA



/**
 * Kategorie generated by hbm2java
 */
public class Kategorie  implements java.io.Serializable {


     private Integer id;
     private String nazev;
     private int instituceId;

     /**
      *
      */
     public Kategorie() {
    }

    /**
     *
     * @param nazev
     * @param instituceId
     */
    public Kategorie(String nazev, int instituceId) {
       this.nazev = nazev;
       this.instituceId = instituceId;
    }
   
    /**
     *
     * @return id
     */
    public Integer getId() {
        return this.id;
    }
    
    /**
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }
    /**
     *
     * @return nazev
     */
    public String getNazev() {
        return this.nazev;
    }
    
    /**
     *
     * @param nazev
     */
    public void setNazev(String nazev) {
        this.nazev = nazev;
    }
    /**
     *
     * @return instituceId
     */
    public int getInstituceId() {
        return this.instituceId;
    }
    
    /**
     *
     * @param instituceId
     */
    public void setInstituceId(int instituceId) {
        this.instituceId = instituceId;
    }




}


