package model;
// Generated 15.12.2011 17:22:14 by Hibernate Tools 3.2.1.GA



/**
 * Resitel generated by hbm2java
 */
public class Resitel  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String heslo;
     private String jmeno;
     private String prijmeni;
     private int kategorieId;
     private String stavUctu;
     private int instituceId;

     /**
      *
      */
     public Resitel() {
    }

    /**
     *
     * @param login
     * @param heslo
     * @param jmeno
     * @param prijmeni
     * @param kategorieId
     * @param stavUctu
     * @param instituceId
     */
    public Resitel(String login, String heslo, String jmeno, String prijmeni, int kategorieId, String stavUctu, int instituceId) {
       this.login = login;
       this.heslo = heslo;
       this.jmeno = jmeno;
       this.prijmeni = prijmeni;
       this.kategorieId = kategorieId;
       this.stavUctu = stavUctu;
       this.instituceId = instituceId;
    }
   
    /**
     *
     * @return id
     */
    public Integer getId() {
        return this.id;
    }
    
    /**
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }
    /**
     *
     * @return login
     */
    public String getLogin() {
        return this.login;
    }
    
    /**
     *
     * @param login
     */
    public void setLogin(String login) {
        this.login = login;
    }
    /**
     *
     * @return heslo
     */
    public String getHeslo() {
        return this.heslo;
    }
    
    /**
     *
     * @param heslo
     */
    public void setHeslo(String heslo) {
        this.heslo = heslo;
    }
    /**
     *
     * @return jmeno
     */
    public String getJmeno() {
        return this.jmeno;
    }
    
    /**
     *
     * @param jmeno
     */
    public void setJmeno(String jmeno) {
        this.jmeno = jmeno;
    }
    /**
     *
     * @return prijmeni
     */
    public String getPrijmeni() {
        return this.prijmeni;
    }
    
    /**
     *
     * @param prijmeni
     */
    public void setPrijmeni(String prijmeni) {
        this.prijmeni = prijmeni;
    }
    /**
     *
     * @return kategorieId
     */
    public int getKategorieId() {
        return this.kategorieId;
    }
    
    /**
     *
     * @param kategorieId
     */
    public void setKategorieId(int kategorieId) {
        this.kategorieId = kategorieId;
    }
    /**
     *
     * @return stavUctu
     */
    public String getStavUctu() {
        return this.stavUctu;
    }
    
    /**
     *
     * @param stavUctu
     */
    public void setStavUctu(String stavUctu) {
        this.stavUctu = stavUctu;
    }
    /**
     *
     * @return instituceId
     */
    public int getInstituceId() {
        return this.instituceId;
    }
    
    /**
     *
     * @param instituceId
     */
    public void setInstituceId(int instituceId) {
        this.instituceId = instituceId;
    }




}


