package model;
// Generated 15.12.2011 17:22:14 by Hibernate Tools 3.2.1.GA



/**
 * Poznamka generated by hbm2java
 */
public class Poznamka  implements java.io.Serializable {


     private int ukolId;
     private int uzivatelId;
     private String nazev;

     /**
      *
      */
     public Poznamka() {
    }

     /**
      *
      * @param ukolId
      * @param uzivatelId
      * @param nazev
      */
     public Poznamka(int ukolId, int uzivatelId, String nazev) {
       this.ukolId = ukolId;
       this.uzivatelId = uzivatelId;
       this.nazev = nazev;
    }
   
     /**
      *
      * @return ukolId
      */
     public int getUkolId() {
        return this.ukolId;
    }
    
     /**
      *
      * @param ukolId
      */
     public void setUkolId(int ukolId) {
        this.ukolId = ukolId;
    }
    /**
     *
     * @return uzivatelId
     *
     */
    public int getUzivatelId() {
        return this.uzivatelId;
    }
    
    /**
     *
     * @param uzivatelId
     */
    public void setUzivatelId(int uzivatelId) {
        this.uzivatelId = uzivatelId;
    }
    /**
     *
     * @return nazev
     */
    public String getNazev() {
        return this.nazev;
    }
    
    /**
     *
     * @param nazev
     */
    public void setNazev(String nazev) {
        this.nazev = nazev;
    }




}


