package model;
// Generated 15.12.2011 17:22:14 by Hibernate Tools 3.2.1.GA



/**
 * Ukol generated by hbm2java
 */
public class Ukol  implements java.io.Serializable {


     private Integer id;
     private String datumPrijeti;
     private String datumSplneni;
     private String nadpis;
     private String textUkolu;
     private String stavUkolu;
     private int uzivatelId;
     private int resitelId;
     private int kategorieId;
     private int instituceId;

     /**
      *
      */
     public Ukol() {
    }

     /**
      *
      * @param datumPrijeti
      * @param datumSplneni
      * @param nadpis
      * @param textUkolu
      * @param stavUkolu
      * @param uzivatelId
      * @param resitelId
      * @param kategorieId
      * @param instituceId
      */
     public Ukol(String datumPrijeti, String datumSplneni, String nadpis, String textUkolu, String stavUkolu, int uzivatelId, int resitelId, int kategorieId, int instituceId) {
       this.datumPrijeti = datumPrijeti;
       this.datumSplneni = datumSplneni;
       this.nadpis = nadpis;
       this.textUkolu = textUkolu;
       this.stavUkolu = stavUkolu;
       this.uzivatelId = uzivatelId;
       this.resitelId = resitelId;
       this.kategorieId = kategorieId;
       this.instituceId = instituceId;
    }
   
     /**
      *
      * @return id
      */
     public Integer getId() {
        return this.id;
    }
    
    /**
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }
    /**
     *
     * @return DatumPrijeti
     */
    public String getDatumPrijeti() {
        return this.datumPrijeti;
    }
    
    /**
     *
     * @param datumPrijeti
     */
    public void setDatumPrijeti(String datumPrijeti) {
        this.datumPrijeti = datumPrijeti;
    }
    /**
     *
     * @return DatumSplneni
     */
    public String getDatumSplneni() {
        return this.datumSplneni;
    }
    
    /**
     *
     * @param datumSplneni
     */
    public void setDatumSplneni(String datumSplneni) {
        this.datumSplneni = datumSplneni;
    }
    /**
     *
     * @return nadpis
     */
    public String getNadpis() {
        return this.nadpis;
    }
    
    /**
     *
     * @param nadpis
     */
    public void setNadpis(String nadpis) {
        this.nadpis = nadpis;
    }
    /**
     *
     * @return textUkolu
     */
    public String getTextUkolu() {
        return this.textUkolu;
    }
    
    /**
     *
     * @param textUkolu
     */
    public void setTextUkolu(String textUkolu) {
        this.textUkolu = textUkolu;
    }
    /**
     *
     * @return stavUkolu
     */
    public String getStavUkolu() {
        return this.stavUkolu;
    }
    
    /**
     *
     * @param stavUkolu
     */
    public void setStavUkolu(String stavUkolu) {
        this.stavUkolu = stavUkolu;
    }
    /**
     *
     * @return uzivatelId
     */
    public int getUzivatelId() {
        return this.uzivatelId;
    }
    
    /**
     *
     * @param uzivatelId
     */
    public void setUzivatelId(int uzivatelId) {
        this.uzivatelId = uzivatelId;
    }
    /**
     *
     * @return resitelId
     */
    public int getResitelId() {
        return this.resitelId;
    }
    
    /**
     *
     * @param resitelId
     */
    public void setResitelId(int resitelId) {
        this.resitelId = resitelId;
    }
    /**
     *
     * @return kategorieId
     */
    public int getKategorieId() {
        return this.kategorieId;
    }
    
    /**
     *
     * @param kategorieId
     */
    public void setKategorieId(int kategorieId) {
        this.kategorieId = kategorieId;
    }
    /**
     *
     * @return instituceId
     */
    public int getInstituceId() {
        return this.instituceId;
    }
    
    /**
     *
     * @param instituceId
     */
    public void setInstituceId(int instituceId) {
        this.instituceId = instituceId;
    }




}


