package model;
// Generated 15.12.2011 17:22:14 by Hibernate Tools 3.2.1.GA



/**
 * Uzivatel generated by hbm2java
 */
public class Uzivatel  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String heslo;
     private String jmeno;
     private String prijmeni;
     private String stavUctu;
     private int roleId;
     private int instituceId;

     /**
      *
      */
     public Uzivatel() {
    }

    /**
     *
     * @param login
     * @param heslo
     * @param jmeno
     * @param prijmeni
     * @param stavUctu
     * @param roleId
     * @param instituceId
     */
    public Uzivatel(String login, String heslo, String jmeno, String prijmeni, String stavUctu, int roleId, int instituceId) {
       this.login = login;
       this.heslo = heslo;
       this.jmeno = jmeno;
       this.prijmeni = prijmeni;
       this.stavUctu = stavUctu;
       this.roleId = roleId;
       this.instituceId = instituceId;
    }
   
    /**
     *
     * @return
     */
    public Integer getId() {
        return this.id;
    }
    
    /**
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }
    /**
     *
     * @return
     */
    public String getLogin() {
        return this.login;
    }
    
    /**
     *
     * @param login
     */
    public void setLogin(String login) {
        this.login = login;
    }
    /**
     *
     * @return
     */
    public String getHeslo() {
        return this.heslo;
    }
    
    /**
     *
     * @param heslo
     */
    public void setHeslo(String heslo) {
        this.heslo = heslo;
    }
    /**
     *
     * @return
     */
    public String getJmeno() {
        return this.jmeno;
    }
    
    /**
     *
     * @param jmeno
     */
    public void setJmeno(String jmeno) {
        this.jmeno = jmeno;
    }
    /**
     *
     * @return
     */
    public String getPrijmeni() {
        return this.prijmeni;
    }
    
    /**
     *
     * @param prijmeni
     */
    public void setPrijmeni(String prijmeni) {
        this.prijmeni = prijmeni;
    }
    /**
     *
     * @return
     */
    public String getStavUctu() {
        return this.stavUctu;
    }
    
    /**
     *
     * @param stavUctu
     */
    public void setStavUctu(String stavUctu) {
        this.stavUctu = stavUctu;
    }
    /**
     *
     * @return
     */
    public int getRoleId() {
        return this.roleId;
    }
    
    /**
     *
     * @param roleId
     */
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    /**
     *
     * @return
     */
    public int getInstituceId() {
        return this.instituceId;
    }
    
    /**
     * 
     * @param instituceId
     */
    public void setInstituceId(int instituceId) {
        this.instituceId = instituceId;
    }




}


